GOOSE_PROVIDER: google
OLLAMA_HOST: localhost
extensions:
  developer:
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
GOOSE_MODEL: gemini-2.0-flash
