model: gemini:gemini-1.5-flash-latest # Specify the LLM to use
clients:
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
  - type: gemini
    api_base: https://generativelanguage.googleapis.com/v1beta
    patch:
      chat_completions:
        ".*":
          body:
            safetySettings:
              - category: HARM_CATEGORY_HARASSMENT
                threshold: BLOCK_NONE
              - category: HARM_CATEGORY_HATE_SPEECH
                threshold: BLOCK_NONE
              - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
                threshold: BLOCK_NONE
              - category: HARM_CATEGORY_DANGEROUS_CONTENT
                threshold: BLOCK_NONE
